name: .NET Build & Lint

on:
  push:
    branches: ['**']     # Triggers on push to any branch
  pull_request:
    branches: ['**']     # Triggers on PR to any branch
  workflow_dispatch:

jobs:
  build:
    name: Build and Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        working-directory: ./POE Part 3 PROG 6221/ST10449143_PROGPOEPART3
        run: dotnet restore

      - name: Build solution
        working-directory: ./POE Part 3 PROG 6221/ST10449143_PROGPOEPART3
        run: dotnet build --no-restore --configuration Release

      - name: Run tests (optional)
        working-directory: ./POE Part 3 PROG 6221/ST10449143_PROGPOEPART3
        run: dotnet test --no-build --verbosity normal
        continue-on-error: true  # Remove if you want the build to fail on test errors
