# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Build & Lint

on:
  push:
    branches: 
      - '**'     # Triggers on push to any branch
  pull_request:
    branches: 
      - '**'     # Triggers on PR to any branch
  workflow_dispatch:

jobs:
  build:
    name: Build and Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore POE Part 3 PROG 6221/POE Part 3 PROG 6221.sln

      - name: Build solution
        run: dotnet build POE Part 3 PROG 6221/POE Part 3 PROG 6221.sln --no-restore --configuration Release

      - name: Run tests (optional)
        run: dotnet test POE Part 3 PROG 6221/POE Part 3 PROG 6221.sln --no-build --verbosity normal
        continue-on-error: true  # Remove if you want the build to fail on test errors
